apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mas-disallow-pod-template-hash
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Disallow Pod Template Hash
    policies.kyverno.io/category: Maximo Application Suite - Other
    policies.kyverno.io/subject: Pod,Deployment,StatefulSet
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Prevent pod-template-hash from being manually added to deployment objects to prevent a
      runaway condition in replicasets and pods.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-pod-template-hash
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
              namespaces:
                - "mas-*-core"
                - "mas-*-assist"
                - "mas-*-facilities"
                - "mas-*-iot"
                - "mas-*-manage"
                - "mas-*-monitor"
                - "mas-*-optimizer"
                - "mas-*-predict"
                - "mas-*-visualinspection"
                - "sls-*"
                - "ibm-sls"
                - "ibm-dro"
                - "redhat-marketplace"
                - "db2u"
      validate:
        message: Cannot add pod-template-hash manually.
        pattern:
          spec:
            selector:
              matchLabels:
                X(pod-template-hash): "*?"
