apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mas-require-image-digest
  annotations:
    policies.kyverno.io/title: Require Images Use Digests
    policies.kyverno.io/category: Maximo Application Suite - Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Use of a SHA checksum when pulling an image is often preferable because tags
      are mutable and can be overwritten. This policy checks to ensure that all images
      use SHA checksums rather than tags.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-image-digest
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - "mas-*-core"
                - "mas-*-assist"
                - "mas-*-facilities"
                - "mas-*-iot"
                - "mas-*-manage"
                - "mas-*-monitor"
                - "mas-*-optimizer"
                - "mas-*-predict"
                - "mas-*-visualinspection"
                - "sls-*"
                - "ibm-sls"
      preconditions:
        any:
          - key: "{{ request.object.metadata.labels.\"app.kubernetes.io/managed-by\" || '' }}"
            operator: NotEquals
            value: olm
          - key: "{{ (request.object.metadata.labels.\"app.kubernetes.io/managed-by\" == 'olm') && (request.object.spec.containers[*].image | join(',') | contains(@, 'icr.io')) }}"
            operator: Equals
            value: true
      validate:
        message: "Images must use checksums rather than tags."
        pattern:
          spec:
            containers:
              - image: "*@sha256:*"
