apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/
nameSuffix: -enforce
patches:
  - target:
      kind: ClusterPolicy
    patch: |-
      - op: replace
        path: /spec/validationFailureAction
        value: Enforce
      - op: replace
        path: /spec/rules/0/match/any/0/resources/namespaceSelector/matchExpressions/0
        value:
          key: ibm.com/kyverno
          operator: In
          value: ['enforce']
