apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mas-disallow-node-selection
  annotations:
    policies.kyverno.io/title: Disallow node selection
    policies.kyverno.io/category: Maximo Application Suite - Other
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      The Kubernetes scheduler uses complex logic to determine the optimal placement
      for new Pods. Users who have access to set certain fields in a Pod spec
      may sidestep this logic which in many cases is undesirable. This policy
      prevents users from targeting specific Nodes for scheduling of Pods by
      prohibiting the use of the `nodeSelector` and `nodeName` fields.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-nodeselector
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - "mas-*-core"
                - "mas-*-assist"
                - "mas-*-facilities"
                - "mas-*-iot"
                - "mas-*-manage"
                - "mas-*-monitor"
                - "mas-*-optimizer"
                - "mas-*-predict"
                - "mas-*-visualinspection"
                - "sls-*"
                - "ibm-sls"
      validate:
        message: Setting the nodeSelector field is prohibited.
        pattern:
          spec:
            X(nodeSelector): "null"

    - name: restrict-nodename
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: Equals
            value: CREATE
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - "mas-*-core"
                - "mas-*-assist"
                - "mas-*-facilities"
                - "mas-*-iot"
                - "mas-*-manage"
                - "mas-*-monitor"
                - "mas-*-optimizer"
                - "mas-*-predict"
                - "mas-*-visualinspection"
                - "sls-*"
                - "ibm-sls"
      exclude:
        any:
          - resources:
              namespaces:
                - "mas-*-core"
                - "mas-*-assist"
                - "mas-*-facilities"
                - "mas-*-iot"
                - "mas-*-manage"
                - "mas-*-monitor"
                - "mas-*-optimizer"
                - "mas-*-predict"
                - "mas-*-visualinspection"
                - "sls-*"
                - "ibm-sls"
      validate:
        message: Setting the nodeName field is prohibited.
        pattern:
          spec:
            X(nodeName): "null"
