apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ford-require-high-availability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    policies.kyverno.io/title: Require Multiple Replicas
    policies.kyverno.io/category: App
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      Deployments with a single replica cannot be highly available and thus the application
      may suffer downtime if that one replica goes down.This policy validates that Deployments
      have more than one replica.
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: deployment-has-multiple-replicas
      match:
        resources:
          kinds:
            - Deployment
            - Deployment/scale
            - StatefulSet
            - StatefulSet/scale
          namespaces:
            - "mas-*-core"
            - "mas-*-assist"
            - "mas-*-facilities"
            - "mas-*-iot"
            - "mas-*-manage"
            - "mas-*-monitor"
            - "mas-*-optimizer"
            - "mas-*-predict"
            - "mas-*-visualinspection"
            - "sls-*"
            - "ibm-sls"
            - "ibm-dro"
            - "redhat-marketplace"
            - "db2u"
      validate:
        message: "StatefulSets/Deployments should have more than one replica to ensure availability."
        pattern:
          spec:
            replicas: ">=2 | 0"