---
# Additional permissions requried by kyverno for the MAS policies
# Warning: system:serviceaccount:kyverno:kyverno-reports-controller requires permissions get,list,watch for resource Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:reports-controller-extras
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:reports-controller-extras
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:reports-controller-extras
subjects:
- kind: ServiceAccount
  name: kyverno-reports-controller
  namespace: kyverno
