apiVersion: apps/v1
kind: Deployment
metadata:
  name: gooddeployment
  namespace: mas-dev-core
  labels:
    app: myapp
spec:
  template:
    spec:
      containers:
      - name: goproxy
        image: registry.k8s.io/goproxy:0.1
        readinessProbe:
          httpGet:
            path: /probes/readiness
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /probes/liveness
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 9
        startupProbe:
          httpGet:
            path: /probes/liveness
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baddeployment
  namespace: mas-dev-core
  labels:
    app: myapp
spec:
  template:
    spec:
      containers:
        - name: goproxy
          image: registry.k8s.io/goproxy:0.1
          readinessProbe:
            httpGet:
              path: /probes/liveness
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /probes/liveness
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /probes/liveness
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 15
